# Generated by Django 2.1.2 on 2018-10-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
