# Generated by Django 2.1.2 on 2018-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumb",
            field=models.ImageField(blank=True, upload_to="covers/"),
        )
    ]
