# Generated by Django 2.1.2 on 2018-11-29 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20181129_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='BookHolder',
        ),
    ]
