# Generated by Django 2.1.2 on 2018-10-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20181018_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='/media/covers/cover_placeholder.png', upload_to='covers/'),
        ),
    ]
