# Generated by Django 2.1.2 on 2018-11-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books", "0004_auto_20181129_1031")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("AV", "available"),
                    ("OL", "on loan"),
                    ("RQ", "requested"),
                    ("NA", "not available"),
                ],
                default="AV",
                max_length=50,
            ),
        )
    ]
