# Generated by Django 2.1.2 on 2018-11-29 23:01

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20181129_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(books.models.LoanStatus('on loan'), 'on loan'), (books.models.LoanStatus('requested'), 'requested'), (books.models.LoanStatus('available'), 'available'), (books.models.LoanStatus('not available'), 'not available')], default='available', max_length=100),
        ),
    ]
