# Generated by Django 2.1.2 on 2018-11-29 23:08

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(books.models.LoanStatus('on loan'), 'on loan'), (books.models.LoanStatus('requested'), 'requested'), (books.models.LoanStatus('available'), 'available'), (books.models.LoanStatus('not available'), 'not available')], default=books.models.LoanStatus('available'), max_length=100),
        ),
    ]
