# Generated by Django 2.1.2 on 2018-11-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookholder',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookholder',
            name='date_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookholder',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
