# Generated by Django 2.1.2 on 2018-12-02 00:58

import books.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20181130_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='holder',
        ),
        migrations.AddField(
            model_name='book',
            name='holders',
            field=models.ManyToManyField(related_name='books_held', through='books.BookHolder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(books.models.get_default_owner), related_name='books_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
