# Generated by Django 2.1.2 on 2018-12-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20181202_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookholder',
            name='status',
            field=models.CharField(default='RQ', max_length=2),
        ),
    ]
