# Generated by Django 2.1.2 on 2018-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20181129_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('on loan', 'on loan'), ('requested', 'requested'), ('available', 'available'), ('not available', 'not available')], default='available', max_length=100),
        ),
    ]
