# Generated by Django 2.1.2 on 2019-01-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190114_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character         <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=17, null=True, verbose_name='ISBN'),
        ),
    ]
