# Generated by Django 2.1.2 on 2018-11-29 23:47

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20181129_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(books.models.LoanStatus('on loan'), 'OL'), (books.models.LoanStatus('requested'), 'RQ'), (books.models.LoanStatus('available'), 'AV'), (books.models.LoanStatus('not available'), 'NA')], default='AV', max_length=100),
        ),
    ]
