# Generated by Django 2.1.5 on 2019-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20190118_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, null=True, verbose_name='ISBN'),
        ),
    ]
