# Generated by Django 2.2 on 2019-05-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20190319_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
