# Generated by Django 2.1.2 on 2018-11-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20181129_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('OL', 'on loan'), ('RQ', 'requested'), ('AV', 'available'), ('NA', 'not available')], max_length=100),
        ),
    ]
