# Generated by Django 2.2 on 2019-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='at_framework',
            field=models.BooleanField(default=False),
        ),
    ]
