# Generated by Django 2.2 on 2019-06-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_at_framework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_published',
        ),
    ]
