# Generated by Django 2.1.2 on 2018-11-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20181129_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('OL', 'on loan'), ('RQ', 'requested'), ('AV', 'available'), ('NA', 'not available')], default=('AV', 'available'), max_length=50),
        ),
    ]
