# Generated by Django 2.2 on 2019-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
