# Generated by Django 2.2 on 2019-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
