# Generated by Django 2.2.1 on 2019-11-15 02:11

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20191114_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=django_fsm.FSMField(choices=[('AV', 'available'), ('RQ', 'requested'), ('OL', 'on loan'), ('LB', 'loan confirmed'), ('RB', 'returned'), ('NA', 'not available')], default='AV', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookloanevent',
            name='status',
            field=models.CharField(default='RQ', max_length=2),
        ),
    ]
